### ISSUE TITLE
Trigger Element Error when Using this.$()

### ISSUE THREAD

**Issue by Shaneprrlt** [willviles/ember-scrollmagic#2]
I am trying to use this library, and just to get set up, I followed the code you posted in the README. However, when I try to create a new scene object in a component's didInsertElement, I get an error from ScrollMagic saying the element I passed to triggerElement was not found. 

Here's the code for my component: 

```
createScene: Ember.on('didInsertElement', function() {

    const scrollController = this.get('scrollMagic').getController();

    let scene = new ScrollMagic.Scene({
      triggerElement: this.$()
    });

    scene.setTween(TweenLite.fromTo(this.$(), 1, { opacity: 0, opacity: 1 }));

    scrollController.addScene(scene);
  }),
```

and this is the error I am getting from chrome: 

![screen shot 2016-12-13 at 2 21 36 pm](https://cloud.githubusercontent.com/assets/388487/21157614/94a19b90-c13f-11e6-965c-aaed6b8629a9.png)

I've played around with this a few times, and I don't want to use a different method, since I think setting triggerElement to this.$() is the cleanest way of writing that.

I should also note that when I click on the ref to the dom element in the error above, it does correspond to a div that exists. After all, this code is called after didInsertElement.

**Comment by willviles** [comment]
@Shaneprrlt, ScrollMagic is expecting a DOM object to be passed to it, not a jQuery object.

Therefore you've got two options: use either `this.$()[0]` or `this.get('element')`.

I've updated the README to reflect this.

**Comment by Shaneprrlt** [comment]
@willviles Thanks! That worked. However, I am still getting one error, I've updated my code a bit.

```
createScene: Ember.on('didInsertElement', function() {

    const scrollController = this.get('scrollMagic').getController();

    let elem = this.$()[0],
      scene = new ScrollMagic.Scene({
        triggerElement: elem
      });

    scene.setTween(TweenLite.fromTo(elem, 1, { opacity: 0, opacity: 1 }));
    scrollController.addScene(scene);
  }),
```

And I'm still getting a similar error in the startAt call with TweenLite.

<img width="823" alt="screen shot 2016-12-14 at 9 12 48 am" src="https://cloud.githubusercontent.com/assets/388487/21187439/8d9060ea-c1dd-11e6-9d28-c8ca4e2d87e8.png">

**Comment by willviles** [comment]
No worries!
